version: '3'
services:
  postres_db:
    container_name: "postres_db"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=2001ah2002
      - POSTGRES_DB=my_db_list
    volumes:
      - ./database_data:/var/lib/postgresql/data
  client:
    build: to_do_proj
    ports:
      - "3001:3000"
    restart: always
    command: yarn start
    volumes: # This is where the magic happens!
      - ./to_do_proj:/usr/src/to_do_proj
      - /usr/src/to_do_proj/node_modules/
  server:
    build: backend
    ports:
      - "5000:5000"
    restart: always
    command: yarn start
    environment:
      - EXTERNAL_PORT=5000
      - PGDATABASE=my_db_list
      - PGUSER=dima
      - PGPASSWORD=2001ah2002
      - PGHOST=postres_db
    depends_on:
      - postres_db
    volumes: # This is where the magic happens!
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules/