build:
    docker build -t backend-docker .
run-dev:
    docker run -d -p 3000:5000 -v "C:\Users\gorun\Desktop\Compleate Proj\ToDoList\backend:/usr/src/backend" -v /usr/src/backend/node_modules --rm --name cont-backend backend-docker
stop:
    docker stop cont-backend